name: Run My Security Scripts

on:
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: oraclelinux-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Bash Script
      run: |
        chmod +x sys_info.sh
        ./sys_info.sh

    - name: Run Python Script
      run: |
        python3 login_failed.py || echo "Skipped due to missing logs"
